<a href="https://colab.research.google.com/github/aharshit123456/Numerical-Methods/blob/main/System_of_Linear_Equations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Methods to solve Systems of Linear Equations

## Direct methods

- Gauss Elimination
- GE with Partial Pivoting
- LU Decomposition

## Iterative Methods

- Gauss-Siedel Method
- Jacobi Iteration

In [4]:
import numpy as np

def gauss_elimination(a_matrix, b_matrix):

  # Adding some contingencies
  if a_matrix.shape[0] != a_matrix.shape[1]:
    print("Error: Square matrix not given !")
    return
  if b_matrix.shape[1] > 1 or b_matrix.shape[0] != a_matrix.shape[0]:
    print("Error: Constant vector incorrectly sized")
    return

  # Intialization of necessary variables
  n = len(b_matrix)
  m = n-1
  i = 0
  j = i - 1
  x = np.zeros(n)
  new_line = "\n"

  # Create our augmented matrix
  augmented_matrix = np.concatenate((a_matrix,b_matrix),axis = 1, dtype = float )
  print(f"The intial augmented matrix is: {new_line}{augmented_matrix}")
  print("Solving for the upper-triangular matrix:")

  # Applying GE:
  while i < n:
    if augmented_matrix[i][i] == 0.0:
      print("Divide by zero error")
      return

    for j in range(i+1, n):
      scaling_factor = augmented_matrix[j][i] / augmented_matrix[i][i]
      augmented_matrix[j] = augmented_matrix[j] - (scaling_factor * augmented_matrix[i])
      print(augmented_matrix)

    i = i + 1

  # Backward Substitution:
  x[m] = augmented_matrix[m][n] / augmented_matrix[m][m]

  for k in range(n-2,-1,-1):
    x[k] = augmented_matrix[k][n]

    for j in range(k+1, n):
      x[k] = x[k]/augmented_matrix[k][k]


  # Displaying solution
  print(f"The following x-vector matrix solves the above augmented matrix:")
  for answer in range(n):
    print(f"x{answer} is {x[answer]}")



var_mat = np.array( [[1,1,3], [0,1, 3], [-1,3,0]])
const_mat = np.array([[1],[3],[5]])

gauss_elimination(var_mat,const_mat)

The intial augmented matrix is: 
[[ 1.  1.  3.  1.]
 [ 0.  1.  3.  3.]
 [-1.  3.  0.  5.]]
Solving for the upper-triangular matrix:
[[ 1.  1.  3.  1.]
 [ 0.  1.  3.  3.]
 [-1.  3.  0.  5.]]
[[1. 1. 3. 1.]
 [0. 1. 3. 3.]
 [0. 4. 3. 6.]]
[[ 1.  1.  3.  1.]
 [ 0.  1.  3.  3.]
 [ 0.  0. -9. -6.]]
The following x-vector matrix solves the above augmented matrix:
x0 is 1.0
x1 is 3.0
x2 is 0.6666666666666666
